version: '3.9'
services:
  bot:
    build: .
    container_name: discord-interactions-bot
    env_file:
      - ./.env.dev
    environment:
      - AWS_REGION=us-east-1
      - NODE_ENV=production
      - DISCORD_TOKEN=/copilot/amplify-discord/local/secrets/DISCORD_TOKEN
      - DISCORD_PUBLIC_KEY=/copilot/amplify-discord/local/secrets/DISCORD_PUBLIC_KEY
      - DISCORD_APP_ID=/copilot/amplify-discord/local/secrets/DISCORD_APP_ID
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - '3000:3000/tcp'
