version: '3.9'
services:
  bot:
    image: bot
    container_name: bot-local
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    expose:
      - '3000'
    volumes:
      - ./apps/bot/db:/usr/src/apps/bot/db
    env_file:
      - .env.local
