Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  ReadParameterStorePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadSecrets
            Effect: Allow
            Action:
              - ssm:Get*
            Resource: '*'

# This will make sure that the tasks in the service will have the permission above.
Outputs:
  ReadParameterStorePolicyArn:
    Description: 'The ARN for policy to read from ssm'
    Value: !Ref ReadParameterStorePolicy
